import {
    LayoutDashboard,
    Users,
    ShieldAlert,
    ScanFace,
    Flag,
    LifeBuoy,
    CreditCard,
    Zap,
    UserCheck,
    Receipt,
    Bell,
    SlidersHorizontal,
    Globe,
} from 'lucide-react';

export const ADMIN_PERMISSIONS = [
    {
        id: 'dashboard',
        label: 'Dashboard',
        path: '/admin/dashboard',
        icon: LayoutDashboard,
        description: 'View dashboard metrics, analytics, user growth and match stats.',
        category: 'Analytics',
    },
    {
        id: 'users',
        label: 'Users',
        path: '/admin/users',
        icon: Users,
        description: 'View, edit, search, and manage registered app user profiles.',
        category: 'User Management',
    },
    {
        id: 'moderation',
        label: 'Moderation',
        path: '/admin/moderation',
        icon: ShieldAlert,
        description: 'Moderate user accounts, ban/unban users, and control account status.',
        category: 'User Management',
    },
    {
        id: 'selfie-verification',
        label: 'Selfie Verification',
        path: '/admin/selfie-verification',
        icon: ScanFace,
        description: 'Review and approve or reject user selfie verification requests.',
        category: 'Verification',
    },
    {
        id: 'reports',
        label: 'Reports & Flags',
        path: '/admin/reports',
        icon: Flag,
        description: 'Inspect user reports, flags, and handle violations.',
        category: 'Moderation',
    },
    {
        id: 'support',
        label: 'Support Management',
        path: '/admin/support',
        icon: LifeBuoy,
        description: 'Respond to and manage user support tickets and inquiries.',
        category: 'Support',
    },
    {
        id: 'subscriptions',
        label: 'Subscriptions Edit',
        path: '/admin/subscriptions',
        icon: CreditCard,
        description: 'Edit pricing, features, and plans for premium subscriptions.',
        category: 'Billing',
    },
    {
        id: 'boost-edit',
        label: 'Boost Edit',
        path: '/admin/boost-edit',
        icon: Zap,
        description: 'Manage boost plans, multiplier rates, and durations.',
        category: 'Billing',
    },
    {
        id: 'subscription-users',
        label: 'Subscription Users',
        path: '/admin/subscription-users',
        icon: UserCheck,
        description: 'View active premium subscribers and grant manual premium status.',
        category: 'Billing',
    },
    {
        id: 'transactions',
        label: 'Transactions',
        path: '/admin/transactions',
        icon: Receipt,
        description: 'View financial transaction logs, payments, and receipts.',
        category: 'Billing',
    },
    {
        id: 'notifications',
        label: 'Notifications',
        path: '/admin/notifications',
        icon: Bell,
        description: 'Send mass push notifications and broadcast alerts to users.',
        category: 'Marketing',
    },
    {
        id: 'app-config',
        label: 'App Config',
        path: '/admin/app-config',
        icon: SlidersHorizontal,
        description: 'Configure app system parameters, gender ratios, and global settings.',
        category: 'System',
    },
    {
        id: 'website-pages',
        label: 'Website Pages',
        path: '/admin/website-pages/privacy-policy',
        icon: Globe,
        description: 'Edit static legal documents like Privacy Policy & Terms of Service.',
        category: 'CMS',
    },
];

export const ALL_PERMISSION_IDS = ADMIN_PERMISSIONS.map((p) => p.id);
